version: '3'
services:
  authembed:
    build: .
    env_file: .env
    environment:
      - 'HOST=0.0.0.0'
    ports:
      - $DOCKER_COMPOSE_WEB_PORT:2010
    restart: unless-stopped

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /data/authembed/mongo/data/db:/data/db
    restart: unless-stopped
