import { registerAs, ConfigType } from '@nestjs/config';

export const authConfig = registerAs('auth', () => ({
  jwtSecret: process.env.JWT_SECRET,
  registrationSuccessRedirectUrl: process.env.REGISTRATION_SUCCESS_REDIRECT_URL,
  emailSuccessfullyVerifiedRedirectUrl:
    process.env.EMAIL_SUCCESSFULLY_VERIFIED_REDIRECT_URL,

  autogeneratedPasswordOptions: JSON.parse(
    process.env.AUTOGENERATED_PASSWORD_OPTIONS ||
      '{"length": 10, "type": "distinguishable"}',
  ) as { length?: number; type?: string },

  adminPassword: process.env.ADMIN_PASSWORD,
}));

export const AUTH_CONFIG_KEY = authConfig.KEY;

export type TAuthConfig = ConfigType<typeof authConfig>;
