import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type AuthWithAutogeneratedPasswordDocument = AuthWithAutogeneratedPasswordModel &
  Document;

@Schema({
  minimize: false,
  collection: 'email_verifications',
})
export class AuthWithAutogeneratedPasswordModel {
  _id: Types.ObjectId;

  @Prop({ type: Date })
  createdAt: Date;

  @Prop({ type: String, required: true })
  email: string;

  @Prop({ type: String, required: true })
  status: 'SUCCESS' | 'PENDING';

  @Prop({ type: Object })
  registrationData?: {
    email: string;
    passwordHash: string;
    name: string;
    metadata?: Record<string, unknown> | null;
  };
}

export const AuthWithAutogeneratedPasswordSchema = SchemaFactory.createForClass(
  AuthWithAutogeneratedPasswordModel,
);
