import {
  Body,
  Controller,
  Get,
  Inject,
  Param,
  Post,
  Query,
  Res,
  UseGuards,
} from '@nestjs/common';
import { AuthService } from './auth.service';
import { StartRegistrationRequestBodyDto } from './dtos/start-registration-request-body.dto';
import { TAuthConfig, AUTH_CONFIG_KEY } from '../config/auth.config';
import { Types } from 'mongoose';
import { Response } from 'express';
import { LoginRequestBodyDto } from './dtos/login-request-body.dto';
import { LocalGuard } from './guards/local.guard';
import { CurrentUser } from './decorators/current-user.decorator';
import { UserDocument } from '../users/schemas/user.schema';
import { ApiBody } from '@nestjs/swagger';
import { RegisterWithAuthgeneratedPasswordSentToMailRequestBodyDto } from './dtos/register-with-autogenerated-password-sent-to-mail-request-body.dto';
import { UpdateAutogeneratedPasswordRequestBodyDto } from './dtos/update-autogenerated-password-request-body.dto';

@Controller()
export class AuthController {
  constructor(
    private readonly authService: AuthService,
    @Inject(AUTH_CONFIG_KEY)
    private readonly authConfigs: TAuthConfig,
  ) {}

  @Post('api/login')
  @UseGuards(LocalGuard)
  @ApiBody({ type: () => LoginRequestBodyDto })
  async login(
    @CurrentUser() user: UserDocument,
    @Res({ passthrough: true }) response: Response,
  ): Promise<any> {
    const accessToken = await this.authService.createAccessToken(user._id);

    response.cookie('authembed_access_token', accessToken);

    return {
      accessToken,
      user,
    };
  }

  @Post('api/auth/register-with-autogenerated-password-sent-to-mail')
  async registerWithAutogeneratedPasswordSentToMail(
    @Body() body: RegisterWithAuthgeneratedPasswordSentToMailRequestBodyDto,
  ): Promise<any> {
    await this.authService.registerWithAutogeneratedPasswordSentToMail(body);
  }

  @Post('api/auth/update-autogenerated-password')
  async updateAutogeneratedPassword(
    @Body() body: UpdateAutogeneratedPasswordRequestBodyDto,
  ): Promise<any> {
    await this.authService.updateAutogeneratedPassword(body);
  }

  @Post('api/auth/register-with-lazy-email-verification')
  async registerWithLazyEmailVerification(
    @Body() body: StartRegistrationRequestBodyDto,
    @Res({ passthrough: true }) response: Response,
  ): Promise<any> {
    const {
      accessToken,
      user,
    } = await this.authService.registerWithLazyEmailVerification(body);

    response.cookie('authembed_access_token', accessToken);

    return {
      accessToken,
      user,
    };
  }

  @Post('api/auth/register-with-email-verification')
  async registerWithEmailVerification(
    @Body() body: StartRegistrationRequestBodyDto,
  ): Promise<any> {
    const {
      emailVerificationId,
    } = await this.authService.registerWithEmailVerification(body);

    return { emailVerificationId };
  }

  @Get('api/users-by-token/:token')
  async getUserByToken(@Param('token') token: string): Promise<any> {
    return await this.authService.getUserByToken(token);
  }

  @Get('auth/email/verify-and-register')
  async verifyEmailAndRegister(
    @Query('id') id: string,
    @Query('code') code: string,
    @Res({ passthrough: true }) response: Response,
  ): Promise<any> {
    const { accessToken } = await this.authService.verifyEmailAndRegister({
      emailVerificationId: Types.ObjectId.createFromHexString(id),
      verificationCode: code,
    });

    response.cookie('authembed_access_token', accessToken);
    response.redirect(this.authConfigs.registrationSuccessRedirectUrl);
  }

  @Get('auth/email/verify')
  async verifyEmail(
    @Query('id') id: string,
    @Query('code') code: string,
    @Res({ passthrough: true }) response: Response,
  ): Promise<any> {
    await this.authService.verifyEmail({
      emailVerificationId: Types.ObjectId.createFromHexString(id),
      verificationCode: code,
    });

    response.redirect(this.authConfigs.emailSuccessfullyVerifiedRedirectUrl);
  }
}
